name: GPT Command Runner

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Shell command to execute'
        required: true

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Command
        run: ${{ github.event.inputs.command }}
