name: Self Check

on:
  push:
    branches:
      - main

jobs:
  self-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key (optional)
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Run self-check script
      run: |
        chmod +x ./self-check.sh
        ./self-check.sh
